name: C/C++ CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install-cmake 
      uses: Symbitic/install-cmake@v0.1.0
      with:
        cmake: 3.17.2
        ninja: 1.9.0
        platform: linux
    - name: cmake-configure
      run: cmake .
    - name: cmake-build
      run: cmake --build .
